services:
  - type: web
    name: email-verifier
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 app:app"
    instances: 1
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
